nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['<http://localhost:4200>']  # Permite solicitudes desde Angular
        allow_headers: ['Content-Type', 'Authorization']  # Puedes añadir más cabeceras si es necesario
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']  # Métodos HTTP permitidos
        max_age: 3600  # Opcional, controla cuánto tiempo se cachea la política CORS en el navegador

    # Puedes configurar otras rutas si es necesario
    paths:
        '^/cancion':  # Habilita CORS para todas las rutas que empiecen con /cancion
            allow_origin: ['http://localhost:4200']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization']
            max_age: 3600
